### PR TITLE
Initial draft of ERD

### PR DESCRIPTION
**Pull request by Fahi28**
Add any suggestions to add/remove stuff.

### CODE REVIEW

**Review by qrafiq1 — COMMENTED** [review]
Should of mentioned this before, but the project requires users to only ''subscribe to earthquake alerts for specific regions and magnitudes''. Maybe we store what the region and magnitude the user is subscribing to in the user table. OR like a topic table, that has topic_id, location_id, and then min_magnitude?

**Review by jiuliangut — CHANGES_REQUESTED** [review]
Looks great! Just the tiniest detail - i've been penalised before for not including the number of chars in varchar()! maybe specify this for email, detail_url, and region_name, particularly since you have done this elsewhere

**Comment by Jakub-Poskrop** [comment]
Do we need to store tsunami? I'm not sure what the group decided on, if so we need to add that to the extract script.

**Review by jiuliangut — APPROVED** [review]
looks great!

**Review by Jakub-Poskrop — APPROVED** [review]
Looks good :).

**Review by S1mpySloth — APPROVED** [review]
Looks good, changes and feedback have been incorporated accordingly!

**Pull request merged**
