### PR TITLE
#76 api tests

### LINKED ISSUE #76: Write tests for API
### Description

Create the test suite for `api.py` to ensure endpoints are returning the expected information and that errors are handled gracefully.

--- 

### Outcome

A `test_api.py` file in the `api` directory containing the tests for the API.

---

### User Story 

As developers, it is important to test our code thoroughly to ensure that it is functioning as expected.

### PR DESCRIPTION
**Pull request by Jakub-Poskrop**
Closes #76 - Created tests for API endpoints. Let me know if I missed something.

### CODE REVIEW

**Review by Fahi28 — APPROVED** [review]
Very thorough testing, nice job!

**Review by jiuliangut — COMMENTED** [review]
Looks really good! could maybe just add a module docstring for consistency with other files?

**Comment by Jakub-Poskrop** [comment]
> Looks really good! could maybe just add a module docstring for consistency with other files?

All done

**Review by Fahi28 — APPROVED** [review]
very thorough testing! good job!

**Review by jiuliangut — APPROVED** [review]
Looks great :)

**Review by jiuliangut — APPROVED** [review]

**Review by S1mpySloth — APPROVED** [review]
Thorough tests! Great stuff

**Pull request merged**
